# Generated by Django 2.0.8 on 2019-05-20 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0003_curso_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
