# Generated by Django 2.0.8 on 2019-05-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0006_auto_20190522_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='curso',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ead.Curso'),
            preserve_default=False,
        ),
    ]
