# Generated by Django 2.0.8 on 2019-02-01 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_i', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_start_acao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_conclusao_acao', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('prazo', models.DateTimeField(default=django.utils.timezone.now)),
                ('objetivo', models.CharField(max_length=400)),
                ('motivo', models.CharField(blank=True, max_length=400, null=True)),
                ('custo', models.CharField(blank=True, max_length=200, null=True)),
                ('atividade', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_area', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=300)),
                ('data_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('acao_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Acao')),
                ('acesso_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Acesso_r')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('assunto', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('pauta', models.CharField(blank=True, default=1, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Status_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_r', models.CharField(default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reuniao',
            name='status_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Status_r'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='tipo_reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Tipo_r'),
        ),
        migrations.AddField(
            model_name='acesso_r',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Reuniao'),
        ),
        migrations.AddField(
            model_name='acesso_r',
            name='tipo_acesso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniao.Tipo_acesso'),
        ),
        migrations.AddField(
            model_name='acao',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Area'),
        ),
        migrations.AddField(
            model_name='acao',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Indicador'),
        ),
        migrations.AddField(
            model_name='acao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acao',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Reuniao'),
        ),
        migrations.AddField(
            model_name='acao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniao.Status'),
        ),
    ]
