# Generated by Django 2.0.8 on 2019-02-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planoacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='acao',
            name='reuniao',
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_conclusao_acao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_start_acao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='pauta',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='planoacao',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniao.Reuniao'),
        ),
        migrations.AddField(
            model_name='acao',
            name='planoacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniao.Planoacao'),
            preserve_default=False,
        ),
    ]
