# Generated by Django 2.0.8 on 2019-02-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0002_auto_20190212_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='reuniao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniao.Reuniao'),
            preserve_default=False,
        ),
    ]
