# Generated by Django 2.0.8 on 2019-02-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0003_acao_reuniao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acao',
            name='indicador',
        ),
    ]
