# Generated by Django 2.0.8 on 2019-02-13 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0004_remove_acao_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='data_inicioprevisto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
