# Generated by Django 2.0.8 on 2019-04-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ccusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccusto_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('chave_despesa', models.CharField(max_length=100)),
                ('ccusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Ccusto')),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('chave_meta', models.CharField(max_length=100)),
                ('ccusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Ccusto')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Conta')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='chave_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Meta'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Conta'),
        ),
        migrations.AddField(
            model_name='ccusto',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Responsavel'),
        ),
        migrations.AddField(
            model_name='ccusto',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Unidade'),
        ),
    ]
