# Generated by Django 2.0.8 on 2019-04-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='chave_meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Meta'),
            preserve_default=False,
        ),
    ]
