# Generated by Django 2.0.8 on 2019-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0002_auto_20190415_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='chave_meta',
        ),
    ]
