# Generated by Django 2.0.8 on 2019-04-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0005_remove_despesa_chave_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='chave_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Meta'),
        ),
    ]
