# Generated by Django 2.0.8 on 2019-04-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0006_despesa_chave_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='chave_meta',
        ),
    ]
