# Generated by Django 2.0.8 on 2019-04-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0008_despesa_key_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='key_meta',
        ),
        migrations.AddField(
            model_name='despesa',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Responsavel'),
        ),
    ]
