# Generated by Django 2.0.8 on 2019-04-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0009_auto_20190415_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='despesa',
            name='chave_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Meta'),
        ),
    ]
