# Generated by Django 2.0.8 on 2019-04-24 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0010_auto_20190415_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('chave_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Meta')),
            ],
        ),
    ]
