# Generated by Django 2.0.8 on 2019-05-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0012_unidade_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='ccusto',
            name='regional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regional', to='gmcdalert.Responsavel'),
        ),
        migrations.AlterField(
            model_name='ccusto',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='gmcdalert.Responsavel'),
        ),
    ]
