# Generated by Django 2.0.8 on 2019-05-24 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0013_auto_20190521_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccusto',
            name='regional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
