# Generated by Django 2.0.8 on 2019-05-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0014_auto_20190524_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccusto',
            old_name='regional',
            new_name='gerente',
        ),
    ]
