# Generated by Django 2.0.8 on 2019-02-20 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='datan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
