# Generated by Django 2.0.8 on 2019-02-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0002_user2_datan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user2',
            name='datan',
        ),
    ]
