# Generated by Django 2.0.8 on 2019-02-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0003_remove_user2_datan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='datan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
