# Generated by Django 2.0.8 on 2019-02-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0004_user2_datan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='datan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
