# Generated by Django 2.0.8 on 2019-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0005_auto_20190220_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
