# Generated by Django 2.0.8 on 2019-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0006_auto_20190220_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='matricula',
            field=models.CharField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
