# Generated by Django 2.0.8 on 2019-04-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0008_auto_20190429_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user2',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Cargo'),
        ),
        migrations.AlterField(
            model_name='user2',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Setor'),
        ),
    ]
