# Generated by Django 2.0.8 on 2019-06-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmcdalert', '0015_auto_20190524_1434'),
        ('lauto', '0010_auto_20190610_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='ccusto',
            field=models.ForeignKey(default=157, on_delete=django.db.models.deletion.CASCADE, to='gmcdalert.Ccusto'),
        ),
    ]
