# Generated by Django 2.0.8 on 2019-06-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lauto', '0013_auto_20190612_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_classe', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_veiculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_veiculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoveiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Classe')),
                ('marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Marca')),
                ('modelo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Modelo')),
                ('setor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Setor')),
                ('tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lauto.Tipoveiculo')),
            ],
        ),
    ]
