# Generated by Django 2.0.8 on 2019-06-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rateio', models.TextField()),
                ('observacao', models.TextField()),
                ('document', models.FileField(upload_to='documents/contas')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_submissao', models.DateTimeField(blank=True, null=True)),
                ('data_fiscalizacao', models.DateTimeField(blank=True, null=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to=settings.AUTH_USER_MODEL)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagador', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to=settings.AUTH_USER_MODEL)),
                ('submissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoconta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_a_pagar.Tipoconta'),
        ),
    ]
