# Generated by Django 2.0.8 on 2019-06-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_vencimento',
            field=models.DateField(),
        ),
    ]
