# Generated by Django 2.0.8 on 2019-06-13 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0003_auto_20190613_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='submissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissor', to=settings.AUTH_USER_MODEL),
        ),
    ]
