# Generated by Django 2.0.8 on 2019-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0004_auto_20190613_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='document',
            field=models.FileField(upload_to='documents/contas/%Y/%m'),
        ),
    ]
