# Generated by Django 2.0.8 on 2019-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0005_auto_20190614_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
