# Generated by Django 2.0.8 on 2019-06-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0008_conta_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
