# Generated by Django 2.0.8 on 2019-06-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas_a_pagar', '0009_conta_motivo_cancelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cancelador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancelador', to=settings.AUTH_USER_MODEL),
        ),
    ]
